### PR TITLE
Add information on how to use implicit TLS

### LINKED ISSUE #24: Prefer TLS over STARTTLS
[RFC 8314](https://tools.ietf.org/html/rfc8314) recommends that you prefer implicit TLS on port 465 over STARTTLS on 587:

>    o  TLS version 1.2 or greater be used for all traffic between MUAs
>       and Mail Submission Servers, and also between MUAs and Mail Access
>       Servers.
> 
>    o  MUAs and Mail Service Providers (MSPs) (a) discourage the use of
>       cleartext protocols for mail access and mail submission and
>       (b) deprecate the use of cleartext protocols for these purposes as
>       soon as practicable.
> 
>    o  Connections to Mail Submission Servers and Mail Access Servers be
>       made using "Implicit TLS" (as defined below), in preference to
>       connecting to the "cleartext" port and negotiating TLS using the
>       STARTTLS command or a similar command.

So I would at least recommend changing the GMail port used. I'm not sure what if any other changes are needed to be made to the document.

### PR DESCRIPTION
**Pull request by remyabel**
Fixes #24

### CODE REVIEW

**Comment by imthenachoman** [comment]
Something is fishy. I deleted the cert files to see what would happen and the e-mail still went through. I will have to play with this some more.

**Comment by remyabel** [comment]
Deleting the certs won't prevent the mail from going through, but there won't be any encryption I don't think. Here's what I get with `openssl s_client -connect localhost:465` before/after deleting the certs:

```
CONNECTED(00000003)
depth=0 C = US, CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, CN = localhost
verify return:1
# etc...

CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
# etc...
```

**Comment by imthenachoman** [comment]
So according to `tcpdump`, it does look like this makes the request through 465. It fails if `openssl` is not installed. And it works after `openssl` is installed even before a cert is created. But to your point, it would still work but wouldn't be encrypted. I will investigate how to confirm if it is being encrypted.

This is great stuff by the way. Thank you so much!

**Comment by imthenachoman** [comment]
`sendmail -v` shows some interesting details. Will investigate more.

**Comment by remyabel** [comment]
Using swaks these are my results:

```
remyabel@instance-1:~$ sudo swaks --protocol smtps -tlsc --tls-cert /etc/exim4/exim.crt --tls-key /etc/exim4/exim.key -q HELO -s localhost
=== Trying localhost:465...
=== Connected to localhost.
=== TLS started with cipher TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256
=== TLS local DN="/C=US/CN=localhost"
=== TLS peer DN="/C=US/CN=localhost"
# ...snip
remyabel@instance-1:~$ sudo swaks --protocol smtps -tlsc --tls-cert /etc/exim4/exim.crt --tls-key /etc/exim4/exim.key -q HELO -s localhost:25
=== Trying localhost:25...
=== Connected to localhost.
*** TLS startup failed (connect(): error:1408F10B:SSL routines:ssl3_get_record:wrong version number)
```

`tlsc` means TLS on connect. So it demonstrates that it does do TLS on port 465 and refuses to connect on port 25. If we do `sudo swaks --protocol smtp -q HELO -s localhost`, then it will do unencrypted transport on port 25 if for some reason someone wants to do that.

**Pull request merged**
